const SUCCESS_TRANSACTION = 1712799;
const WAITING_CONFIRM = 1712813;
const MessageTypeEnum = {
    CREATE_CONNECTION: 0,
    UPDATE_ALL: 1,
    UPDATE_TRANSACTION_POOL: 2,
    ADD_EVENT: 3,
    ACCEPT_EVENT: 4,
    DISBURSEMENT: 5,
    FORCE_END_EVENT: 6,
    
    UI_UPDATE_BLOCKCHAIN: 1001,
    UI_UPDATE_POOL: 1002,
    UI_ADD_EVENT: 1003,
    UI_ACCEPT_EVENT: 1004,
    UI_DISBURSEMENT: 1005,
    UI_FORCE_END_EVENT: 1006,

}
module.exports = {
    SUCCESS_TRANSACTION,
    WAITING_CONFIRM,
    MessageTypeEnum
}